// ─── CARD CONFIGURATIONS ──────────────────────────────────────────────────────

const CARD_TYPES = {
  RLL: {
    label: 'RLL 37/38',
    docNo: 'RLL-BHC-001',
    rev: 'REV 2',
    revDate: '2025-09-30',
    hasOpticalSight: false,
    hasSightMovement: false,
    extraFields: [],
    checks: [
      { id:'c01', label:'Cylinder Spacer Size — Front',  type:'measurement', unit:'mm' },
      { id:'c02', label:'Cylinder Spacer Size — Rear',   type:'measurement', unit:'mm' },
      { id:'c03', label:'Spacer Friction Size — Front',  type:'measurement', unit:'mm' },
      { id:'c04', label:'Spacer Friction Size — Rear',   type:'measurement', unit:'mm' },
      { id:'c05', label:'Flash Gap: GO & NO-GO',         type:'go_nogo' },
      { id:'c06', label:'Manual Advance',                type:'pass_fail' },
      { id:'c07', label:'Cylinder Alignment',            type:'pass_fail' },
      { id:'c08', label:'Cylinder Torque',               type:'pass_fail' },
      { id:'c09', label:'Trigger Pull',                  type:'pass_fail' },
      { id:'c10', label:'Firing Pin Protrusion',         type:'pass_fail' },
      { id:'c11', label:'Centre Lock Pin-Lock',          type:'pass_fail' },
      { id:'c12', label:'Headspace',                     type:'pass_fail' },
      { id:'c13', label:'Front Grip',                    type:'pass_fail' },
      { id:'c14', label:'Rear Stiffness',                type:'pass_fail' },
      { id:'c15', label:'Barrel: GO & NO-GO',            type:'go_nogo' },
      { id:'c16', label:'Stock Movement',                type:'pass_fail' },
      { id:'c17', label:'Cylinder Torque-Sim',           type:'pass_fail' },
      { id:'c18', label:'General Finish',                type:'pass_fail' },
    ]
  },

  XRGL40: {
    label: 'XRGL40',
    docNo: 'XRGL-BHC-001',
    rev: 'REV 5',
    revDate: '2025-09-30',
    hasOpticalSight: true,
    hasSightMovement: true,
    extraFields: ['sight_serial','hfm_prod_no','hrc_prod_no'],
    checks: [
      { id:'c01', label:'Cylinder Spacer Size — Front',  type:'measurement', unit:'mm' },
      { id:'c02', label:'Cylinder Spacer Size — Rear',   type:'measurement', unit:'mm' },
      { id:'c03', label:'Spacer Friction Size — Front',  type:'measurement', unit:'mm' },
      { id:'c04', label:'Spacer Friction Size — Rear',   type:'measurement', unit:'mm' },
      { id:'c05', label:'Flash Gap: GO & NO-GO',         type:'go_nogo' },
      { id:'c06', label:'Manual Advance',                type:'pass_fail' },
      { id:'c07', label:'Cylinder Alignment',            type:'pass_fail' },
      { id:'c08', label:'Cylinder Torque',               type:'pass_fail' },
      { id:'c09', label:'Trigger Pull',                  type:'pass_fail' },
      { id:'c10', label:'Firing Pin Protrusion',         type:'pass_fail' },
      { id:'c11', label:'Centre Lock Pin-Lock',          type:'pass_fail' },
      { id:'c12', label:'Headspace',                     type:'pass_fail' },
      { id:'c13', label:'Front Grip',                    type:'pass_fail' },
      { id:'c14', label:'Rear Stiffness',                type:'pass_fail' },
      { id:'c15', label:'Sight Movement',                type:'pass_fail' },
      { id:'c16', label:'Barrel: GO & NO-GO',            type:'go_nogo' },
      { id:'c17', label:'Stock Movement',                type:'pass_fail' },
      { id:'c18', label:'Cylinder Torque-Sim',           type:'pass_fail' },
      { id:'c19', label:'General Finish',                type:'pass_fail' },
    ]
  },

  GRN40: {
    label: 'GRN40',
    docNo: 'GRN-BHC-001',
    rev: 'REV 2',
    revDate: '2025-09-30',
    hasOpticalSight: true,
    hasSightMovement: false,
    extraFields: ['sight_serial'],
    // GRN40 uses sub-assembly stages instead of pass/fail checks
    stages: [
      { id:'s01', col:0, label:'PCB GRN40 ASSY', process:'PROGRAMMING',  partNo:'7171440V3' },
      { id:'s02', col:0, label:'PCB GRN40 ASSY', process:'COATING',      partNo:'7171440V3' },
      { id:'s03', col:0, label:'PCB GRN40 ASSY', process:'TESTING',      partNo:'7171440V3' },
      { id:'s04', col:0, label:'BATTERY PCB ASSY',process:'',            partNo:'717142120' },
      { id:'s05', col:0, label:'BATTERY CAP ASSY',process:'',            partNo:'105-03-000' },
      { id:'s06', col:0, label:'CLICKER ASSY (2)',process:'',            partNo:'1E1-4A-AB' },
      { id:'s07', col:0, label:'MEMBRANE SWITCH-Testing',process:'',     partNo:'105-01-007' },
      { id:'s08', col:0, label:'OPTICAL ASSY',   process:'',             partNo:'717141516' },
      { id:'s09', col:1, label:'RANGE PLATE ASSY LH', process:'ENGRAVING', partNo:'105-00-001' },
      { id:'s10', col:1, label:'RANGE PLATE ASSY RH', process:'ENGRAVING', partNo:'105-00-0012' },
      { id:'s11', col:1, label:'RETICLE HOUSING ASSY', process:'',       partNo:'1E1-4A-FD' },
      { id:'s12', col:1, label:'TUBE ASSY',      process:'LENS',         partNo:'1E1-4A-AC' },
      { id:'s13', col:1, label:'TUBE ASSY',      process:'RETICLE',      partNo:'1E1-4A-AC' },
      { id:'s14', col:1, label:'TUBE ASSY',      process:'WINDOW',       partNo:'1E1-4A-AC' },
      { id:'s15', col:1, label:'TUBE ASSY',      process:'LEAK TEST',    partNo:'1E1-4A-AC' },
      { id:'s16', col:2, label:'SIGHT BODY ASSY',process:'PROCESS 1',    partNo:'105-01-000' },
      { id:'s17', col:2, label:'SIGHT BODY ASSY',process:'PROCESS 2',    partNo:'105-01-000' },
      { id:'s18', col:2, label:'SIGHT BODY ASSY',process:'PROCESS 3',    partNo:'105-01-000' },
      { id:'s19', col:2, label:'SIGHT BODY ASSY',process:'PROCESS 4',    partNo:'105-01-000' },
      { id:'s20', col:2, label:'GRN40 SIGHT',   process:'FINAL ASSY',    partNo:'105-00-000' },
      { id:'s21', col:2, label:'GRN40 SIGHT',   process:'ZEROING',       partNo:'105-00-000' },
    ]
  }
};
